source 'https://github.com/CocoaPods/Specs.git'

pod 'IGTableViewEstimatedHeightCache/SimpleMagic', :path => "../"

#target 'IGTableViewEstimatedHeightCache', :exclusive => true do
#end
#
target 'Tests', :exclusive => true do
#    pod 'IGTableViewEstimatedHeightCache', :path => "../"
#
  pod 'Kiwi'
end
