source 'https://github.com/CocoaPods/Specs.git'

target 'IGTableViewEstimatedHeightCache', :exclusive => true do
  pod "IGTableViewEstimatedHeightCache", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "IGTableViewEstimatedHeightCache", :path => "../"

  pod 'Kiwi'
end
